# Site settings
title: 我不叫大脸猫的容器研究所
SEOTitle: 我不叫大脸猫的博客 | 我不叫大脸猫的容器研究所
header-img: img/home-bg-o.jpg
email: qxhy123@gmail.com
description: "深入剖析Linux容器 | 我不叫大脸猫，Web & Container Lover，Software Engineer | 这里是 @我不叫大脸猫 qxhy123 的个人博客，与你一起发现更大的世界。"
keyword: "我不叫大脸猫, qxhy123, 博客, 个人网站, 互联网, Web, PHP, 容器, Docker, Golang, Kubernetes, k8s, Service Mesh"
url: "https://qxhy123.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
github_username: qxhy123
zhihu_username: qxhy123
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: qxhy123

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-xxxxxx-1'            # Format: UA-xxxxxx-xx
#ga_domain: qxhy123.github.io

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "时代抛弃你的时候，连声招呼都不会跟你打"
sidebar-avatar: /img/notbigfacecat.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: [
    {
         title: "我不叫大脸猫的容器研究所",
         href: "http://qxhy123.github.io/"
    }
]
